### ISSUE TITLE
Retrieve Memory Protect and Script Control Detection on a Device

### ISSUE THREAD

**Issue by chikme01** [jan-tee/cycli#12]
How do we retrieve Script Control and Memory Protect detection on a device or set of devices.
We want to pull this and take action on the devices.
It would be great, if we could do that.

Thank you

**Comment by jan-tee** [comment]
Unfortunately there is no API available for CyCLI to use that would support
access to these items.

**Comment by chikme01** [comment]
Thanks so much, I have submitted an idea. 
Thanks very much.
