### ISSUE TITLE
Get-CyAPI -Console <consoleID> returns 401 error

### ISSUE THREAD

**Issue by 3133780X** [jan-tee/cycli#13]
I can acquire the access token and auth token with a python script; but when I run Get-CyAPI -Console <consoleID> I get this error:

Get-CyAPI : Could not get valid API token.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\CyAPI.ps1:155 char:17
+                 Get-CyAPI @args
+                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
The remote server returned an error: (401) Unauthorized.

Any help would be greatly appreciated.

**Comment by jan-tee** [comment]
Please provide the full command you are using to create the console
account, and then to use get-cyapi. Replace the confidential bits with
people placeholders of course. Make sure you follow the instructions.

**Comment by 3133780X** [comment]
I am using this command and filling in our company specific details:
New-CyConsoleConfig

I then fill in the tenantID, APIid, APIsecret, etc.

This creates the consoles.json file with everything populated except for the "Token": "" parameter.

At this point I ran Get-CyAPI -Console "our company console ID"

This is when I receive the 401 error fully detailed above.

**Comment by jan-tee** [comment]
1) Are you running Get-CyAPI with the same user ID? That's required because the credentials are protected using DPAPI

2) New-CyConsoleConfig attempts to connect. It apparently succeeds, or it would give you an exception...?

**Comment by 3133780X** [comment]
To my knowledge I am not supplying any specific user ID or credential set for any of these commands except for the API/tenant/secret credentials required for interacting with the Cylance API. 

The New-CyConsoleConfig command appears to succeed; although all I can see it doing is taking my input and creating the consoles.json file from those inputs. 

Please forgive my ignorance. This is my first foray into Cylance and the realm of its API.

**Comment by jan-tee** [comment]
I am talking about the Windows user that runs the Powershell commands.

New-Cy... writes an entry that can only be traf by the same Windows user.

**Comment by 3133780X** [comment]
Yes, this is all being done in the same profile on the same machine logged on as the same windows user.

**Comment by jan-tee** [comment]
Then it is very strange. Can you please remove the consoles.json, return both commands, and use -Verbose as an option, record the output, remove all confidential info, and provide the output?

**Comment by 3133780X** [comment]
COMMAND 1:
PS C:\Users\PROFILE> New-CyConsoleConfig -Verbose
cmdlet New-CyConsoleConfig at command pipeline position 1
Supply values for the following parameters:
Console: <ID>
APIId: <ID>
APITenantId: <ID>

COMMAND 2:
PS C:\Users\PROFILE\Documents\Scripts\cycli-0.5.4> Get-CyAPI -Console CONSOLE_ID
ConvertTo-Base64UrlEncoding : The term 'ConvertTo-Base64UrlEncoding' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Users\PROFILE\Documents\Scripts\cycli-0.5.4\CyCrypto.ps1:72 char:10
+     $h = ConvertTo-Base64UrlEncoding $h_json
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Base64UrlEncoding:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
ConvertTo-Base64UrlEncoding : The term 'ConvertTo-Base64UrlEncoding' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Users\PROFILE\Documents\Scripts\cycli-0.5.4\CyCrypto.ps1:73 char:10
+     $p = ConvertTo-Base64UrlEncoding $p_json
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Base64UrlEncoding:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
ConvertTo-Base64UrlEncoding : The term 'ConvertTo-Base64UrlEncoding' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Users\PROFILE\Documents\Scripts\cycli-0.5.4\CyCrypto.ps1:15 char:5
+     ConvertTo-Base64UrlEncoding $signatureBytes
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Base64UrlEncoding:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-CyAPI : Could not get valid API token.
At C:\Users\PROFILE\Documents\Scripts\cycli-0.5.4\CyAPI.ps1:155 char:17
+                 Get-CyAPI @args
+                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
The remote server returned an error: (401) Unauthorized.

**Comment by jan-tee** [comment]
Why are you using an ancient version and not installing from
Powershellgallery...?

Please have a look at the README

**Comment by 3133780X** [comment]
The only version under releases is the version I pulled down. I do not see where in the README it mentions another method of pulling down another version from another source.

I did a quick search for powershell gallery and I now see some new info. I'll take a look at this and report back. Thanks for your help.

**Comment by jan-tee** [comment]
You can't miss it in the readme, on this site, under code. When you open
GitHub.com/jan-tee/CyCLI/ it is the page that is displayed, same for all
GitHub repos. It has detailed instructions and also links to a repository
with examples.

The old release on the released page is from a time when installing from
GitHub was recommended.

I will remove it to prevent others from having the same issue. There are
2000+ downloads from Powershellgallery though, it's the preferred method
and the README documents that too.

**Comment by 3133780X** [comment]
I now have the current version and am receiving this error:

Get-CyAPI : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyAPI.ps1:180 char:17
+                 Get-CyAPI @rest
+                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
Get-CyAPI : Could not obtain valid API token. This may mean that (a) your API credentials are incorrect or (b) your API 
auth URL is incorrect (use Get-Help Get-CyAPI to get a list of URLs), and your code is attempting to authenticate to the 
wrong global API instance, or (c) the time or time zone on your device is set incorrectly.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyAPI.ps1:180 char:17
+                 Get-CyAPI @rest
+                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
The remote server returned an error: (401) Unauthorized.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyAPI.ps1:143 char:21
+                     throw $_.Exception
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (401) Unauthorized.

**Comment by 3133780X** [comment]
If I attempt to authenticate via the Cylance provided python script using the same details, it is successful.

**Comment by jan-tee** [comment]
That's great but not really indicative of the cause.

You must be missing something. Most likely the -Region parameter for the
console. Did you remove the old consoles.json and recreate it?

**Comment by 3133780X** [comment]
that was part of the problem. I ran the command to recreate the consoles.json file and it asked for the -Region parameter. I entered 'us'. This was the resulting error:
Get-CyAPI : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
Get-CyAPI : Could not obtain valid API token. This may mean that (a) your API credentials are incorrect or (b) 
your API auth URL is incorrect (use Get-Help Get-CyAPI to get a list of URLs), and your code is attempting to 
authenticate to the wrong global API instance, or (c) the time or time zone on your device is set incorrectly.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
The remote server returned an error: (401) Unauthorized.

**Comment by Plloi** [comment]
I'm going to ask the potentially stupid question...

Are you using the App ID or Tenant ID as the Console ID after setting up consoles.json? If so, that's incorrect. This is a user set-able value  you select when you run New-ConsoleConfig

**Comment by 3133780X** [comment]
Thanks for your reply Plloi. I am not using the App/Tenant ID as the Console ID. My app/tenant IDs are acquired from our cylance portal; and the console ID is https://login.cylance.com/Login

**Comment by Plloi** [comment]
That might actually be causing a problem, try using a simple name for the console ID like `CompanyNameCylanceAPI`. The Console ID is just use to identify a configured console by CyCLI and it's value doesn't have to be anything specific.

**Comment by jan-tee** [comment]
The console id is a user-settable value used to identify your console. From the README:

> The Console argument throughout the module is a string that you can use to reference a set of credentials, so you do not have to remember/reference it yourself. An added advantage is that credentials are stored protected by DPAPI and you do not need to worry about accidentally sharing them when sharing your scripts.

In the output you only supplied the output of Get-CyAPI, not the output of the New-CyConsoleConfig command. Please run both with -verbose as the argument, redact any secrets, and send it again.

Please keep in mind that the secret cannot be supplied as a STRING, only as a SecureString, if you intend to pass it as a variable. If you provide it interactively you can copy/paste a string, it will be converted automatically.

**Comment by jan-tee** [comment]
This is the README that also links to examples: https://github.com/jan-tee/cycli

**Comment by 3133780X** [comment]
Thank you for clarifying my misunderstanding regarding the consoleID. 

When I run the New-CyConsoleConfig command with -Verbose I get the following output:

PS C:\Users\PROFILE> New-CyConsoleConfig -Verbose
cmdlet New-CyConsoleConfig at command pipeline position 1
Supply values for the following parameters:
Console: name
APIId: ID
APITenantId: ID
Region: us
VERBOSE: Requesting auth for JWT token: TOKEN
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=True
VERBOSE: Invoking CyREST method using REST params:
VERBOSE: {
    "UserAgent":  "PowerShell/CyCLI",
    "ContentType":  "application/json; charset=utf-8",
    "Method":  "POST",
    "Uri":  "https://protectapi.cylance.com/auth/v2/token",
    "Headers":  {
                    "Accept":  "application/json"
                },
    "OutFile":  "",
    "Body":  "{\r\n    \"auth_token\":  \"TOKEN\"\r\n}"
}
VERBOSE: Body: @{Body=}
VERBOSE: POST https://protectapi.cylance.com/auth/v2/token with -1-byte payload
Get-CyAPI : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
Get-CyAPI : Could not obtain valid API token. This may mean that (a) your API credentials are incorrect or (b) 
your API auth URL is incorrect (use Get-Help Get-CyAPI to get a list of URLs), and your code is attempting to 
authenticate to the wrong global API instance, or (c) the time or time zone on your device is set incorrectly.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI
 
The remote server returned an error: (401) Unauthorized.

**Comment by jan-tee** [comment]
Yes, and if there is no error message and you are using a reasonably
current release (like the official one from Powershellgallery, like you are
based on the thread in this ticket) then that also means it connected to
the console and saved the entry. When you now run get-cyapi <yourconsoleid>
to use the entry, it should work just fine.

**Comment by 3133780X** [comment]
It looks like I am getting the tokens in that output; but there is also an error message. When I ran it again it appeared to work and the subsequent Get-CyAPI -Console <ID> command looks now to have executed without errors. I am running my first API script now and it has not yet thrown an error. So, I think I am in good shape. Thank you both so much for your patience and assistance in this!
