### ISSUE TITLE
API v2 Error

### ISSUE THREAD

**Issue by LechPoznan86** [jan-tee/cycli#2]
The Get-CyDevices commandlet works just fine however if I'm trying to make changes to the console ie. zone/policy assignments I'm getting this error thrown at me. Seen this before?

Invoke-RestMethod : {"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'http://protectapi.us.cylance.com/v2/' does not 
support the API version '2'."}}
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.6.6\CyAPI.ps1:490 char:9
+         Invoke-RestMethod @rest
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by jan-tee** [comment]
No, I have never seen this.

Please repro (using the applicable parameter for "console" in your environment of course):

```powershell
get-cyapi <yourconsoleentry> -Verbose
$zone=New-CyZone -Name Test -Verbose
get-cydevicelist | Add-CyDeviceToZone -Zone $zone -Verbose
```

And report the results back. This would add all devices in your environment to the "test" zone. If you have many devices in your console, you may want to add a "where" filter between get-cydevicelist and the Add-CyDeviceToZone like "where name -like 'COMPUTERNAME'" etc.

**Comment by LechPoznan86** [comment]
PS C:\windows\system32> Get-CyAPI **** -Verbose
VERBOSE: consoles.json path used: C:\Users\****\consoles.json
VERBOSE: consoles.json path used: C:\Users\****\consoles.json
VERBOSE: Requesting auth for JWT token:
****
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=True
VERBOSE: Invoking CyREST method using params:
Name                           Value
----                           -----
UserAgent                      PowerShell/CyCLI
ContentType                    application/json; charset=utf-8
Method                         POST
Uri                            https://protectapi.us.cylance.com/auth/v2/token
Headers                        {Accept}
OutFile
Body                           {...
VERBOSE: POST https://protectapi.us.cylance.com/auth/v2/token with -1-byte payload
VERBOSE: received 822-byte response of content type application/json; charset=utf-8




PS C:\windows\system32> New-CyZone -Name **** -Verbose
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=False
VERBOSE: Renewing token:

AccessToken    :
***
BaseUrl        : https://protectapi.us.cylance.com
APISecret      : System.Security.SecureString
APIId          : ***
APITenantId    : ***
ExpirationTime : 9/14/2018 3:45:42 PM
Scope          : Session

VERBOSE: consoles.json path used: C:\Users\****\consoles.json
VERBOSE: Requesting auth for JWT token:
***
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=True
VERBOSE: Invoking CyREST method using params:
Name                           Value
----                           -----
UserAgent                      PowerShell/CyCLI
ContentType                    application/json; charset=utf-8
Method                         POST
Uri                            https://protectapi.us.cylance.com/auth/v2/token
Headers                        {Accept}
OutFile
Body                           {...
VERBOSE: POST https://protectapi.us.cylance.com/auth/v2/token with -1-byte payload
VERBOSE: received 822-byte response of content type application/json; charset=utf-8
VERBOSE: New token:
AccessToken    :
****
BaseUrl        : https://protectapi.us.cylance.com
APISecret      : System.Security.SecureString
APIId          : ***
APITenantId    : ***
ExpirationTime ***
Scope          : None
VERBOSE: Checkpoint 3
VERBOSE: Invoking CyREST method using params:
Name                           Value
----                           -----
UserAgent                      PowerShell/CyCLI
ContentType                    application/json; charset=utf-8
Method                         POST
Uri                            https://protectapi.us.cylance.com/zones/v2
Headers                        {Accept, Authorization}
OutFile
Body                           {...
VERBOSE: POST https://protectapi.us.cylance.com/zones/v2 with -1-byte payload
VERBOSE: received 187-byte response of content type application/json; charset=utf-8
id           : ***
name         : ***
criticality  : Normal
policy_id    : ***
date_created : ***





PS C:\windows\system32> Add-CyDeviceToZone -Zone *** -device *** -Verbose
VERBOSE: Update device JSON: {
    "name":  null,
    "policy_id":  null,
    "add_zone_ids":  [
                         null
                     ]
}
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=False
VERBOSE: Checkpoint 3
VERBOSE: Invoking CyREST method using params:
Name                           Value
----                           -----
UserAgent                      PowerShell/CyCLI
ContentType                    application/json; charset=utf-8
Method                         PUT
Uri                            https://protectapi.us.cylance.com/devices/v2/
Headers                        {Accept, Authorization}
OutFile
Body                           {...
VERBOSE: PUT https://protectapi.us.cylance.com/devices/v2/ with -1-byte payload
Invoke-RestMethod : {"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI
'http://protectapi.us.cylance.com/v2/' does not support the API version '2'."}}
At C:\Program Files\WindowsPowerShell\Modules\Cycli\0.6.6\CyAPI.ps1:490 char:9
+         Invoke-RestMethod @rest
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by sognern** [comment]
> The Get-CyDevices commandlet works just fine however if I'm trying to make changes to the console ie. zone/policy assignments I'm getting this error thrown at me. Seen this before?
> 
> Invoke-RestMethod : {"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'http://protectapi.us.cylance.com/v2/' does not
> support the API version '2'."}}
> At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.6.6\CyAPI.ps1:490 char:9
> 
> * ```
>       Invoke-RestMethod @rest
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   * CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>   * FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Did you use the device object?
You always need to use objects.
Also make sure that you have write/modify on your application items in integration.

Example:
$CylanceZoneUsers = Get-CyZone -Name "User Zone" 
$devices = Get-CyDeviceList |?{$_.name -like "MACHINES*"}
$devices | Add-CyDeviceToZone -Zone $CylanceZoneUsers -Verbose

You cannot:
Add-CyDeviceToZone -Device "MACHINE" -Zone "User Zone"

**Comment by jan-tee** [comment]
sognern is spot on, and I had tried to express that above. Unfortunately there's not much I can do with the pasted output because it has been redacted and doesn't seem to be the output from the exact commands that I had sent. The bits I do see is that the commands run were slightly different from the ones I had asked for - _Add-CyDeviceToZone -Zone *** -device *** -Verbose_ is a different use and without knowing the *** it's impossible to know if the command is valid. If the *** are names, it is definitely incorrect use of the parameters and will and should fail.

**Comment by jrremillard** [comment]
Hi,
I am getting this error when trying to add-cydevicetozone -device "devicename" -zone "zone_name"
Invoke-RestMethod : {"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'http://protectapi.cylance.com/v2/' does not support the API version '2'
Any help would be great
