### ISSUE TITLE
Readme is not correct (last section)

### ISSUE THREAD

**Issue by Boerner1337** [jan-tee/cycli#5]
$threats = Get-CyDeviceList | Get-CyDeviceThreats
$threatDetails = $threats.sha256 | Get-CyThreatDetails

There is no module called Get-CyDeviceThreats (you probably meant Get-CyDeviceThreatList) 
Typo in Get-CyThreatDetails  (meaning Get-CyThreatDetail) 

Cheers,

**Comment by jan-tee** [comment]
Resolved in latest commit, added additional example for getting all threats since a new API was released
