### ISSUE TITLE
set-cypolicyfordevice

### ISSUE THREAD

**Issue by jrremillard** [jan-tee/cycli#6]
Hi,

When trying to apply policy to device using the above function i get an error

Policy object does not contain 'id' property.

here is what i use
Set-CyPolicyForDevice -device JFZRTQ2 -policy 3a84648c-187b-4b08-90a9-c885eaaf8e8a
i have also used the policy friendly name instead of its id.

thoughts?

**Comment by sognern** [comment]
You cannot specify just name, you need to use the object.
I would guess that this would work:
$devices = Get-CyDeviceList |?{$_.name -like "FilterMachineName*"}
$devices | Set-CyPolicyForDevice -policy 3a84648c-187b-4b08-90a9-c885eaaf8e8a

**Comment by jrremillard** [comment]
Thank you but i receive the same error
$devices = Get-CyDeviceList |?{$_.name -eq "JFZRTQ2"} | select -first 1

PS C:\Powershell> $devices | Set-CyPolicyForDevice -policy 3a84648c-187b-4b08-90a9-c885eaaf8e8a
Policy object does not contain 'id' property.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.6.6\CyPolicies.ps1:46 char:13
+             throw "Policy object does not contain 'id' property."
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Policy object d... 'id' property.:String) [], RuntimeException
    + FullyQualifiedErrorId : Policy object does not contain 'id' property.

**Comment by sognern** [comment]
Maybe the same applies to policy:

$CylanceTestPolicy = Get-CyPolicyList |? {$_.name -eq "Test Policy"}
$Devices |Set-CyPolicyForDevice -Policy $CylanceTestPolicy

**Comment by jrremillard** [comment]
Excellent!!!!! That worked... Thank you very much

I am getting a different error when trying to add a device to a zone i will try this way as well for that issue.

really appreciate the help.

thanks again.
