### ISSUE TITLE
Get-CyDeviceList returns 404, other transactions are fine

### ISSUE THREAD

**Issue by bbevard** [jan-tee/cycli#9]
I started getting errors accessing the API this morning.  I have no issues running get-cypolicylist or get-cyzonelist. I have checked permissions and I have granted read and modify permissions to the device tables. When I go to pull the device list or interact with devices at all I get the following:

PS C:\Scripts\Cylance> Get-CyDeviceList
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyAPI.ps1:548 char:9
+         Invoke-RestMethod @rest
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by bbevard** [comment]
I just checked one of the canned example files as well (Identify_Duplicate_Devices.ps1) and I'm hitting the same errors.  Everything was working on Thursday or Friday of last week.

**Comment by jan-tee** [comment]
Let's focus on the first error you are getting. If there was a change in behavior, there is either a backend problem, or something changed on your end. Did you run "Get-CyAPI" to authenticate with the same console profile you had used earlier prior to running Get-CyDeviceList? Please try running Get-CyAPI and Get-CyDeviceList with -Verbose and please provide the output.

**Comment by bbevard** [comment]
Yes, I ran "Get-CyAPI -Console 'myconsole'" which connected correctly.  I then attempted to start building a new process flow which failed when it tried to pull the device list, so I tried running a script I have been using for the past 4 months that fixes policies on machines that are in a maintenance container and that gave the same error.  I then tried the identify_duplicate_devices.ps1 script I had used a while back and got the same error as well.  I do not have any issues running get-cythreatlist or get-cypolicylist and get the full data back from those.  I just can't run Get-CyDeviceList, Get-CyDevice or Get-CyDeviceByMAC anymore.  My tenant is in us-gov if that makes any difference.  Here is the output from a verbose run:

C:\Scripts\Cylance> Get-CyDeviceList -verbose
VERBOSE: Read-CyData: GET https://protectapi.us.cylance.com/devices/v2 | page = 1
VERBOSE: Read-CyData: GET https://protectapi.us.cylance.com/devices/v2 | page_size = 10000
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=False
VERBOSE: Invoking CyREST method using REST params:
VERBOSE: {
    "UserAgent":  "PowerShell/CyCLI",
    "Method":  "GET",
    "Uri":  "https://protectapi.us.cylance.com/devices/v2",
    "Headers":  {
                    "Accept":  "application/json",
                    "Authorization":  "Bearer
###REDACTED###"
                },
    "OutFile":  "",
    "Body":  {
                 "page":  1,
                 "page_size":  10000
             }
}
VERBOSE: Body: @{Body=}
VERBOSE: GET https://protectapi.us.cylance.com/devices/v2?page=1&page_size=10000 with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.9.7\CyAPI.ps1:548 char:9
+         Invoke-RestMethod @rest
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

VERBOSE: Response was page  of  pages

**Comment by jan-tee** [comment]
Did you update the CyCLI module recently? There was a change in the backend
API to enable support for a new pagesize of 10000 (vs. 200 before). It is
possible that your environment does not support it yet, or that there is a
transient error in the backend. I suggest you open a ticket with Cylance
Support to find out. I don't see anything in the output that looks
incorrect and there have been no other reports so far.

**Comment by bbevard** [comment]
One of the first things I did was update the module on my script server to 0.9.7 but my desktop is running 0.6.6 and it is giving me the same errors.  Prior to updating my script server it was on 0.7.x and I still had the powershell window open from last week so all I had to do was get-cyapi -console 'myconsole' to reconnect and then I hit up a few times to run a command that was working a few lines above, but now it fails with the 404 error.

I just ran get-cydevicelist -verbose on my 0.6.6 system and I'm getting a slightly different output:

VERBOSE: Read-CyData: GET https://protectapi.us.cylance.com/devices/v2 | page = 1
VERBOSE: Read-CyData: GET https://protectapi.us.cylance.com/devices/v2 | page_size = 200
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=False
VERBOSE: Renewing token:

AccessToken    :
##REDACTED##
BaseUrl        : https://protectapi.us.cylance.com
APISecret      : System.Security.SecureString
APIId          : ##REDACTED##
APITenantId    : ##REDACTED##
ExpirationTime : 5/6/2019 4:59:31 PM
Scope          : Session



VERBOSE: consoles.json path used: C:\Users\ekb\consoles.json
VERBOSE: Requesting auth for JWT token:
###REDACTED####
VERBOSE: Entry into Invoke-CyRestMethod: DoNotRenewToken=True
VERBOSE: Invoking CyREST method using params:
Name                           Value

----                           -----

UserAgent                      PowerShell/CyCLI

ContentType                    application/json; charset=utf-8

Method                         POST

Uri                            https://protectapi.us.cylance.com/auth/v2/token

Headers                        {Accept}

OutFile

Body                           {...



VERBOSE: POST https://protectapi.us.cylance.com/auth/v2/token with -1-byte payload
VERBOSE: received 1080-byte response of content type application/json; charset=utf-8
VERBOSE: New token:

AccessToken    :
##REDACTED##
BaseUrl        : https://protectapi.us.cylance.com
APISecret      : System.Security.SecureString
APIId          : ##REDACTED##
APITenantId    : ##REDACTED##
ExpirationTime : 5/6/2019 5:03:28 PM
Scope          : None



VERBOSE: Checkpoint 3
VERBOSE: Invoking CyREST method using params:
Name                           Value

----                           -----

UserAgent                      PowerShell/CyCLI

Method                         GET

Uri                            https://protectapi.us.cylance.com/devices/v2

Headers                        {Accept, Authorization}

OutFile

Body                           {page, page_size}



VERBOSE: GET https://protectapi.us.cylance.com/devices/v2?page=1&page_size=200 with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.6.6\CyAPI.ps1:490 char:9
+         Invoke-RestMethod @rest
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Convert-CyObject : Cannot bind argument to parameter 'CyObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\CyCLI\0.6.6\CyAPI.ps1:292 char:18
+             $_ | Convert-CyObject
+                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Convert-CyObject], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Convert-CyObject

VERBOSE: Response was page  of  pages

**Comment by jan-tee** [comment]
Still looks like backend. Please make sure to change your API Id, as you pasted it above in the verbose mode output (you redacted the token, but not the API Id. I'll remove it if possible).

**Comment by bbevard** [comment]
After set everything up in Postman and created the connections there and showed that it was still failing, Cylance agreed the issue was on their end with the us-gov instance.  Thank you for the assistance.
